name: TeleportHome
version: '${project.version}'
main: org.juan.teleporthome.TeleportHome
api-version: 1.16
depend: [PlaceholderAPI]
softdepend:
  - [Vault]
commands:
  s-home:
    description: To set you home location
  g-home:
    description: To give a home item
  rename:
    description: To rename custom tp item
